/**
 * @file linux_random.h
 * @brief Linux cryptographically secure random interface.
 *
 * This header defines the Linux-specific interface for obtaining
 * cryptographically secure random bytes.
 *
 * The implementation is used by higher-level key and nonce
 * generation code through the common platform abstraction.
 */

#ifndef AESCRYPT_LINUX_RANDOM_H
#define AESCRYPT_LINUX_RANDOM_H

#include <stddef.h>
#include <stdint.h>

/**********************************************************
 * Cryptographically Secure Random Bytes
 **********************************************************/

/*
 * Generate cryptographically secure random bytes.
 *
 * The generated bytes will be used for:
 *
 *       - AES-128 key generation
 *       - AES-CTR nonce generation
 *
 * Parameters:
 *
 *     buffer
 *         Destination buffer receiving random bytes.
 *
 *     size
 *         Number of random bytes requested.
 *
 * Return:
 *
 *     0        on success.
 *     non-zero on failure.
 *
 * On failure:
 *
 *     - Do not assume that the buffer contains valid random data.
 */
int aescrypt_linux_random_bytes(
    uint8_t *buffer,
    size_t size);

/**********************************************************
 * End of File
 **********************************************************/

#endif /* AESCRYPT_LINUX_RANDOM_H */